name: Test Pull Request

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  TERM: xterm-color
  PY_COLORS: 1
  LOG_LEVEL: DEBUG

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.11"
          - "3.12"

    name: Python ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v4

      - name: Install ImageBuilder prereqs
        run: sudo apt-get install -y libncurses5-dev

      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade poetry
          poetry install

      - name: Lint with ruff
        run: |
          poetry run ruff check .

      - name: Stylecheck with ruff
        run: |
          poetry run ruff format --check .

      - name: Test with pytest
        run: |
          docker system service --time=0 unix:///tmp/docker.sock &
          export CONTAINER_HOST="unix:///tmp/docker.sock"
          poetry run coverage run -m pytest -vv --runslow
          poetry run coverage xml

      - name: Codecov
        uses: codecov/codecov-action@v4
